name: 🚀 Deploy to mpes.kesug.com

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy:
    name: 🎉 Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: 📂 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0

        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          server-dir: /htdocs/

          protocol: ftp
          port: 21

          dangerous-clean-slate: false